<?php


namespace app\mobile\controller;


class BaseUc extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = session('xwx_user_id');
        if (is_null($this->uid)){
            $this->redirect(url('account/login'));
        }
    }
}