<?php


namespace app\index\controller;


use app\model\Area;
use app\model\Book;
use app\model\Chapter;
use app\model\Tags;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\facade\Db;
use think\facade\View;

class Booklist extends Base
{
    protected $bookService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        cookie('nav_switch', 'booklist'); //设置导航菜单active
        $this->bookService = app('bookService');
    }

    public function index()
    {
        $cate_selector = '全部';
        $area_selector = '全部';
        $end_selector = '全部';
        $tags = cache('tags');
        if (!$tags) {
            $tags = \app\model\Tags::select();
            cache('tags', $tags, null, 'redis');
        }
        $areas = cache('areas');
        if (!$areas) {
            $areas = \app\model\Area::select();
            cache('areas', $areas, null, 'redis');
        }

        $map = array();
        $area = input('area');
        if (is_null($area) || $area == '-1') {

        } else {
            $area_selector = $area;
            $map[] = ['area_id', '=', $area];
        }
        $tag = input('tag');
        if (is_null($tag) || $tag == '全部') {

        } else {
            $cate_selector = $tag;
            $map[] = ['tags', 'like', '%' . $tag . '%'];
        }
        $end = input('end');
        if (is_null($end) || $end == -1) {

        } else {
            $end_selector = $end;
            $map[] = ['end', '=', $end];
        }
        $data = $this->bookService->getPagedBooks(config('page.booklist_page'), $this->end_point, 'id', $map);

        unset($data['page']['query']['page']);
        $param = '';
        foreach ($data['page']['query'] as $k => $v) {
            $param .= '&' . $k . '=' . $v;
        }
        View::assign([
            'books' => $data['books'],
            'tags' => $tags,
            'areas' => $areas,
            'cate_selector' => $cate_selector,
            'area_selector' => $area_selector,
            'end_selector' => $end_selector,
            'page' => $data['page'],
            'param' => $param
        ]);
        return view($this->tpl);
    }
}