<?php

namespace app\admin\controller;

use app\service\AuthorService;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\facade\View;
use app\model\Author;

class Authors extends BaseAdmin
{
    protected $authorService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->authorService = app('authorService');
    }

    public function index()
    {
        $authorService = new AuthorService();
        $data = $this->authorService->getAuthors();
        View::assign([
            'authors' => $data['authors'],
            'count' => $data['count']
        ]);
        return view();
    }

    public function create()
    {
        if (request()->isPost()) {
            $author_name = input('author_name');
            $author = new Author();
            $author->author_name = $author_name;
            $result = $author->save();
            if ($result) {
                return json(['err' => 0, 'msg' => '添加成功']);
            } else {
                return json(['err' => 1, 'msg' => '添加失败']);
            }
        }
        return view();
    }

    public function edit()
    {
        if (request()->isPost()) {
            $data = request()->param();
            $result = Author::update($data);
            if ($result) {
                return json(['err' =>0,'msg'=>'修改成功']);
            }else{
                return json(['err' =>1,'msg'=>'修改失败']);
            }
        }
        $id = input('id');
        try {
            $author = Author::findOrFail($id);
            View::assign([
                'author' => $author,
            ]);
            return view();
        } catch (DataNotFoundException $e) {
            abort(404, $e->getMessage());
        } catch (ModelNotFoundException $e) {
            abort(404, $e->getMessage());
        }
    }

    public function delete()
    {
        $id = input('id');
        try {
            $author = Author::findOrFail($id);
            $books = $author->books;
            if (count($books) > 0){
                return json(['err' => '1','msg' => '该作者名下还有作品，请先删除所有作品']);
            }
            $result = $author->delete();
            if ($result) {
                return json(['err' => '0','msg' => '删除成功']);
            } else {
                return json(['err' => '1','msg' => '删除失败']);
            }
        } catch (DataNotFoundException $e) {
            abort(404, $e->getMessage());
        } catch (ModelNotFoundException $e) {
            abort(404, $e->getMessage());
        }
    }

    public function deleteAll($ids){
        $ids = input('ids');
        Author::destroy($ids);
    }

    public function getBooksByAuthor($author_name){
        $data = $this->authorService->getBooksByAuthor($author_name); //查出书籍
        View::assign([
            'books' => $data['books'],
            'count' => count($data['books'])
        ]);
        return view('books/index');
    }

    public function search($author_name){
        $data = $this->authorService->getAuthors([
            ['author_name','like','%'.$author_name.'%']
        ]);
        View::assign([
            'authors' => $data['authors'],
            'count' => $data['count']
        ]);
        return view('index');
    }
}