<?php


namespace app\admin\controller;

use app\BaseController;
use think\App;
use think\facade\Env;
use think\facade\View;

class BaseAdmin extends BaseController
{
    protected $prefix;
    protected $site;
    protected $end_point;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (session('xwx_admin') == null) {
            $this->redirect(url('login/login'));
        }
        $this->prefix = Env::get('database.prefix');
        $this->site = config('site.schema').config('site.domain');
        $this->end_point = config('seo.book_end_point');
        View::assign([
            'prefix' => $this->prefix,
            'admin' => cookie('xwx_admin'),
            'cdn' => config('site.cdn'),
            'site' => $this->site
        ]);
    }
}