<?php


namespace app\admin\controller;

use app\model\UserOrder;
use app\service\FinanceService;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\exception\ErrorException;
use think\facade\App;
use think\facade\View;
use app\model\User;
use app\model\UserFinance;
class Payment extends BaseAdmin
{
    protected $financeService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->financeService = app('financeService');
    }

    //支付配置文件
    public function index()
    {
        if (request()->isPost()) {
            $content = input('json');
            try {
                file_put_contents(App::getRootPath() . 'config/payment.php', $content);
                return json(['err' => 0, 'msg' => '保存成功']);
            } catch (ErrorException $exception) {
                return json(['err' => 1, 'msg' => '保存失败，'.$exception]);
            }
        }
        try {
            $content = file_get_contents(App::getRootPath() . 'config/payment.php');
            View::assign('json', $content);
            return view();
        } catch (ErrorException $e) {
            abort(404, $e->getMessage());
        }

    }

    //订单查询
    public function orders()
    {
        $id = input('id');
        $uid = input('uid');
        $status = (int)input('status');
        $map = array();
        if ($id) {
            $map[] = ['id', '=', $id];
        }
        if ($uid) {
            $map[] = ['user_id', '=', $uid];
        }

        if ($status) {
            $map[] = ['status', '=', $status == 2 ? 0 : 1];
        }

        $data = $this->financeService->getPagedOrders($map);
        View::assign([
            'orders' => $data['orders'],
            'count' => $data['count']
        ]);
        return view();
    }

    //用户消费记录
    public function finance()
    {
        $uid = input('uid');
        $usage = input('usage');
        $map = array();
        if ($uid) {
            $map[] = ['user_id', '=', $uid];
        }
        if ($usage) {
            $map[] = ['usage', '=', $usage];
        }
        $data = $this->financeService->getPagedFinance($map);
        View::assign([
            'finances' => $data['finances'],
            'count' => $data['count']
        ]);
        return view();
    }

    //用户购买记录
    public function buy()
    {
        $data = $this->financeService->getPagedBuyHistory();
        View::assign([
            'buys' => $data['buys'],
            'count' => $data['count']
        ]);
        return view();
    }

    public function charge()
    {
        if (request()->isPost()) {
            $uid = input('uid');
            try {
                $user = User::findOrFail($uid);
                $money = input('money');
                $userFinance = new UserFinance();
                $userFinance->user_id = $uid;
                $userFinance->money = $money;
                $userFinance->usage = 1;
                $userFinance->summary = '代充值';
                $result = $userFinance->save();
                if ($result) {
                    return json(['err' => 0, 'msg' => '充值成功']);
                } else {
                    return json(['err' => 1, 'msg' => '充值失败']);
                }
            } catch (DataNotFoundException $e) {
                abort(404, $e->getMessage());
            } catch (ModelNotFoundException $e) {
                abort(404, $e->getMessage());
            }

        }
        return view();
    }

    public function delete() {
        $id = input('id');
        $result = UserOrder::destroy($id);
        if ($result) {
            return ['err' => '0','msg' => '删除成功'];
        } else {
            return ['err' => '1','msg' => '删除失败'];
        }

    }
}