<?php


namespace app\admin\controller;

use app\model\Book;
use think\facade\App;

class Sitemap extends BaseAdmin
{
    protected $books;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $num = config('seo.sitemap_gen_num');
        if ($num <= 0) {
            $this->books = Book::select();
        } else {
            $this->books = Book::order('id', 'desc')->limit($num)->select();
        }

        foreach ($this->books as &$book) {
            if ($this->end_point == 'id') {
                $book['param'] = $book['id'];
            } else {
                $book['param'] = $book['unique_id'];
            }
        }
    }

    public function index()
    {
        $pc_array = $this->create_array('pc');
        $m_array = $this->create_array('m');
        $mip_array = $this->create_array('mip');

        $this->gensitemap($pc_array, 'pc');
        $this->gensitemap($m_array, 'm');
        $this->gensitemap($mip_array, 'mip');

        $this->genurls('pc');
        $this->genurls('m');
        $this->genurls('mip');
        return '<p><a href="/sitemap_pc.xml">pc端网站地图制作成功！点击这里查看</a></p>
                <p><a href="/sitemap_m.xml">移动端网站地图制作成功！点击这里查看</a></p>
                <p><a href="/sitemap_mip.xml">mip端网站地图制作成功！点击这里查看</a></p>
                <p><a href="/pc.txt">pc端地址批量导出到文件！点击这里查看</a></p>
                <p><a href="/m.txt">移动端地址批量导出到文件！点击这里查看</a></p>
                <p><a href="/mip.txt">mip端地址批量导出到文件！点击这里查看</a></p>
                ';
    }

    private function gensitemap($array, $name) {
        $content = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset>\n";
        foreach ($array as $data) {
            $content .= $this->create_item($data);
        }
        $content .= '</urlset>';
        $fp = fopen(App::getRootPath() .'public/sitemap_'.$name.'.xml', 'w+');
        fwrite($fp, $content);
        fclose($fp);
    }

    private function genurls($option) {
        if ($option == 'pc') {
            $site_name = config('site.schema').config('site.domain');
        } else if ($option == 'm') {
            $site_name = config('site.schema').config('site.mobile_domain');
        } else {
            $site_name = config('site.schema').config('site.mip_domain');
        }
        $urls = '';
        foreach ($this->books  as $key => $book) {
            $urls .= $site_name.'/'.BOOKCTRL.'/'.$book->id."\n";
            $fp = fopen(App::getRootPath() .'public/'.$option.'.txt', 'w+');
            fwrite($fp, $urls);
        }
    }

    private function create_array($option){
        if ($option == 'pc') {
            $site_name = config('site.schema').config('site.domain');
        } else if ($option == 'm') {
            $site_name = config('site.schema').config('site.mobile_domain');
        } else {
            $site_name = config('site.schema').config('site.mip_domain');
        }

        $data = array();
        $main = array(
            'loc' => $site_name,
            'priority' => '1.0'
        );
        $booklist= array(
            'loc' => $site_name.'/booklist',
            'priority' => '0.5',
            'lastmod' => date("Y-m-d"),
            'changefreq' => 'yearly'
        );


        foreach ($this->books as $key => $book){ //这里构建所有的内容页数组
            $temp = array(
                'loc' => $site_name.'/'.BOOKCTRL.'/'.$book['param'],
                'priority' => '0.9',
            );
            array_push( $data,$temp);
        }

        array_push($data,$main);
        array_push($data,$booklist);
        return $data;
    }

    private function create_item($data)
    {
        $item = "<url>\n";
        $item .= "<loc>" . $data['loc'] . "</loc>\n";
        $item .= "<priority>" . $data['priority'] . "</priority>\n";
        $item .= "</url>\n";
        return $item;
    }

}